ignn/zinc:
  fw_mitr: 50
  graph_pool: sum
  head_dropout: 0.1
  hidden: 64
  kappa: 0.9
  lr: 0.001
  num_layers: 2
  phi: relu
  row_norm: false
  wd: 0.0001
ignn/peptides_func:
  fw_mitr: 50
  graph_pool: sum
  head_dropout: 0.1
  hidden: 64
  kappa: 0.9
  lr: 0.001
  num_layers: 2
  phi: relu
  row_norm: false
  wd: 0.0001
ignn/peptides_struct:
  fw_mitr: 50
  graph_pool: sum
  head_dropout: 0.1
  hidden: 64
  kappa: 0.9
  lr: 0.001
  num_layers: 2
  phi: relu
  row_norm: false
  wd: 0.0001
ignn/ogbg_molhiv:
  fw_mitr: 50
  graph_pool: sum
  head_dropout: 0.1
  hidden: 128
  kappa: 0.9
  lr: 0.0005
  num_layers: 2
  phi: tanh
  row_norm: true
  wd: 1.0e-05
eignn/zinc:
  dropout: 0.1
  gamma: 0.99
  graph_pool: sum
  head_dropout: 0.0
  hidden: 64
  lr: 0.001
  max_iter: 100
  num_layers: 2
  row_norm: false
  threshold: 0.0001
  wd: 1.0e-05
eignn/peptides_func:
  dropout: 0.1
  gamma: 0.99
  graph_pool: sum
  head_dropout: 0.0
  hidden: 64
  lr: 0.001
  max_iter: 100
  num_layers: 2
  row_norm: false
  threshold: 0.0001
  wd: 1.0e-05
eignn/peptides_struct:
  dropout: 0.4
  gamma: 0.99
  graph_pool: sum
  head_dropout: 0.1
  hidden: 96
  lr: 0.001
  max_iter: 100
  num_layers: 1
  row_norm: false
  threshold: 1.0e-06
  wd: 0.0001
eignn/ogbg_molhiv:
  dropout: 0.4
  gamma: 0.99
  graph_pool: sum
  head_dropout: 0.1
  hidden: 96
  lr: 0.001
  max_iter: 100
  num_layers: 1
  row_norm: false
  threshold: 1.0e-06
  wd: 0.0001
mgnni/zinc:
  dropout: 0.1
  gamma: 0.99
  graph_pool: sum
  head_dropout: 0.0
  hidden: 64
  lr: 0.001
  max_iter: 100
  num_layers: 2
  row_norm: false
  threshold: 0.0001
  wd: 1.0e-05
mgnni/peptides_func:
  dropout: 0.1
  gamma: 0.99
  graph_pool: sum
  head_dropout: 0.0
  hidden: 64
  lr: 0.001
  max_iter: 100
  num_layers: 2
  row_norm: false
  threshold: 0.0001
  wd: 1.0e-05
mgnni/peptides_struct:
  dropout: 0.1
  gamma: 0.99
  graph_pool: sum
  head_dropout: 0.0
  hidden: 64
  lr: 0.001
  max_iter: 100
  num_layers: 2
  row_norm: false
  threshold: 0.0001
  wd: 1.0e-05
mgnni/ogbg_molhiv:
  dropout: 0.0
  gamma: 0.7
  graph_pool: mean
  head_dropout: 0.0
  hidden: 128
  lr: 0.0005
  max_iter: 100
  num_layers: 1
  row_norm: false
  threshold: 0.0001
  wd: 1.0e-05
monotone_mignn/zinc:
  dropout: 0.0
  graph_pool: mean
  head_bias: false
  head_dropout: 0.1
  hidden: 64
  lr: 0.001
  max_iter: 100
  nonlin: relu
  num_layers: 3
  post_ig_act: true
  row_norm: false
  tol: 1.0e-05
  wd: 1.0e-05
monotone_mignn/peptides_func:
  dropout: 0.0
  graph_pool: mean
  head_bias: false
  head_dropout: 0.1
  hidden: 64
  lr: 0.001
  max_iter: 100
  nonlin: relu
  num_layers: 3
  post_ig_act: true
  row_norm: false
  tol: 1.0e-05
  wd: 1.0e-05
monotone_mignn/peptides_struct:
  dropout: 0.0
  graph_pool: sum
  head_bias: true
  head_dropout: 0.1
  hidden: 96
  lr: 0.001
  max_iter: 100
  nonlin: relu
  num_layers: 1
  post_ig_act: false
  row_norm: false
  tol: 1.0e-05
  wd: 0.0001
monotone_mignn/ogbg_molhiv:
  dropout: 0.0
  graph_pool: mean
  head_bias: false
  head_dropout: 0.1
  hidden: 64
  lr: 0.001
  max_iter: 100
  nonlin: relu
  num_layers: 3
  post_ig_act: true
  row_norm: false
  tol: 1.0e-05
  wd: 1.0e-05
gind/zinc:
  act_imp: relu
  alpha: 0.145
  double_linear: true
  dropout_exp: 0.0
  dropout_imp: 0.0
  graph_pool: add
  head_dropout: 0.0
  hidden: 96
  lr: 0.001
  norm: InstanceNorm
  num_layers: 1
  wd: 1.0e-05
gind/peptides_func:
  act_imp: tanh
  alpha: 0.145
  double_linear: true
  dropout_exp: 0.0
  dropout_imp: 0.0
  graph_pool: add
  head_dropout: 0.2
  hidden: 128
  lr: 0.0001
  norm: InstanceNorm
  num_layers: 3
  wd: 1.0e-05
gind/peptides_struct:
  act_imp: relu
  alpha: 0.145
  double_linear: true
  dropout_exp: 0.4
  dropout_imp: 0.4
  graph_pool: add
  head_dropout: 0.2
  hidden: 128
  lr: 0.0005
  norm: InstanceNorm
  num_layers: 1
  wd: 1.0e-05
gind/ogbg_molhiv:
  act_imp: relu
  alpha: 0.145
  double_linear: true
  dropout_exp: 0.0
  dropout_imp: 0.0
  graph_pool: add
  head_dropout: 0.0
  hidden: 96
  lr: 0.001
  norm: InstanceNorm
  num_layers: 1
  wd: 1.0e-05
ignn_finite_loop/zinc:
  T: 16
  activation: relu
  dropout: 0.2
  graph_pool: sum
  head_dropout: 0.1
  hidden: 96
  lr: 0.001
  num_layers: 1
  row_norm: false
  wd: 0.0001
ignn_finite_loop/peptides_func:
  T: 4
  activation: relu
  dropout: 0.0
  graph_pool: mean
  head_dropout: 0.1
  hidden: 64
  lr: 0.0005
  num_layers: 1
  row_norm: true
  wd: 0.0001
ignn_finite_loop/peptides_struct:
  T: 16
  activation: relu
  dropout: 0.2
  graph_pool: sum
  head_dropout: 0.1
  hidden: 96
  lr: 0.001
  num_layers: 1
  row_norm: false
  wd: 0.0001
ignn_finite_loop/ogbg_molhiv:
  T: 4
  activation: relu
  dropout: 0.0
  graph_pool: mean
  head_dropout: 0.1
  hidden: 64
  lr: 0.0005
  num_layers: 1
  row_norm: true
  wd: 0.0001
adagim/zinc:
  K_max: 10
  alpha: 1.0
  gate_lambda_nowrite: 0.01
  gate_lambda_sharp: 0.01
  gate_tau_init: 0.1
  gate_temp: 1.0
  graph_pool: sum
  head_dropout: 0.1
  hidden: 128
  lr: 0.0001
  num_layers: 3
  phi: relu
  row_norm: true
  s_W: 0.9
  wd: 0.0001
adagim/peptides_func:
  K_max: 10
  alpha: 1.0
  gate_lambda_nowrite: 0.0
  gate_lambda_sharp: 0.01
  gate_tau_init: 0.1
  gate_temp: 1.0
  graph_pool: sum
  head_dropout: 0.0
  hidden: 128
  lr: 0.0001
  num_layers: 3
  phi: tanh
  row_norm: true
  s_W: 0.9
  wd: 1.0e-05
adagim/peptides_struct:
  K_max: 20
  alpha: 0.5
  gate_lambda_nowrite: 0.0
  gate_lambda_sharp: 0.0
  gate_tau_init: 1.0
  gate_temp: 0.5
  graph_pool: sum
  head_dropout: 0.1
  hidden: 96
  lr: 0.0005
  num_layers: 3
  phi: relu
  row_norm: true
  s_W: 0.9
  wd: 0.0001
adagim/ogbg_molhiv:
  K_max: 30
  alpha: 0.5
  gate_lambda_nowrite: 0.0
  gate_lambda_sharp: 0.01
  gate_tau_init: 1.0
  gate_temp: 0.5
  graph_pool: sum
  head_dropout: 0.0
  hidden: 64
  lr: 0.0005
  num_layers: 2
  phi: tanh
  row_norm: true
  s_W: 0.99
  wd: 1.0e-05
